# Generated by Django 5.2.6 on 2025-09-27 21:36

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_number'),
        ('products', '0002_category_cat_active_name_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country', 'state', 'city'], name='address_location_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postal_code', 'country'], name='address_postal_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['full_name'], name='address_name_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='order_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='order_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='order_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['status', '-created_at'], name='order_active_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_created_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='order_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_reference'], name='order_payment_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['currency', 'status', 'created_at'], name='order_currency_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['grand_total'], name='order_total_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('grand_total__gte', Decimal('1000.00'))), fields=['-grand_total', '-created_at'], name='order_high_value_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_address', 'status'], name='order_shipping_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(condition=models.Q(('is_active', True), ('status__in', ['PENDING', 'PAID'])), fields=['-created_at'], name='order_pending_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orderitem_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product', 'quantity'], name='orderitem_product_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product', 'line_total'], name='orderitem_product_total_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['unit_price'], name='orderitem_unit_price_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(condition=models.Q(('quantity__gte', 5)), fields=['product', '-quantity'], name='orderitem_bulk_orders_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(condition=models.Q(('line_total__gte', Decimal('500.00'))), fields=['-line_total'], name='orderitem_high_value_idx'),
        ),
    ]
